### ISSUE TITLE
Add new Air Fryer 4l

### ISSUE THREAD

**Issue by Nebur692** [tsunglung/XiaomiAirFryer#11]
Good morning,

Please can you add the new 4 liter fryer?

Model: careli.fryer.maf05a

Thanks.

**Comment by kejXero** [comment]
I second that request :-)

**Comment by ManuBoss55** [comment]
Still no news?

**Comment by carlituxman** [comment]
me too

**Comment by danielszilagyi** [comment]
The device id is already committed into the code:

https://github.com/tsunglung/XiaomiAirFryer/commit/dcb227fe68adcf0556870656b52f341fbd111e88

I pulled master, set it up with local IP and the token via GUI, and seems to return data. Control also works, started the last manually set program with the switch. Thanks for the integration!

![image](https://github.com/tsunglung/XiaomiAirFryer/assets/76160997/1905ec46-d1c6-4c6f-8b27-ae9218fc278b)



`

**Comment by AlexGreenUK** [comment]
@danielszilagyi Hi, Maybe you can help.

I have my Device IP and the Token and I go to add it manually but then I get this error

'''
Logger: aiohttp.server
Source: components/xiaomi_miio/device.py:60 
First occurred: 19:11:04 (2 occurrences) 
Last logged: 19:12:28

Error handling request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/device.py", line 53, in async_connect_device
    self._device_info = await self._hass.async_add_executor_job(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/click_common.py", line 183, in _wrap
    self._fetch_info()
  File "/usr/local/lib/python3.11/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 10.0.1.137

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_airfryer/config_flow.py", line 280, in async_step_cloud
    return await self.async_step_connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_airfryer/config_flow.py", line 333, in async_step_connect
    await connect_device_class.async_connect_device(self.host, self.token)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/device.py", line 60, in async_connect_device
    raise SetupException(
homeassistant.components.xiaomi_miio.const.SetupException: DeviceException during setup of xiaomi device with host 10.0.1.137
'''

Thanks for any help

**Comment by AlexGreenUK** [comment]
> > @danielszilagyi Hi, Maybe you can help.
> > I have my Device IP and the Token and I go to add it manually but then I get this error
> > homeassistant.components.xiaomi_miio.const.SetupException: DeviceException during setup of xiaomi device with host 10.0.1.137
> 
> Hi,
> 
> I would try a `pip install python-miio` and then `miiocli discover`in the HA container, or web terminal, or any applicable system in the same network and see where it goes. My devices were found with discovery properly.

@danielszilagyi 

Thanks for the reply.

Just tried it and got,

,,,
INFO:miio.miioprotocol:Sending discovery to <broadcast> with timeout of 5s..
INFO:miio.miioprotocol:Discovery done
INFO:miio.discovery:Discovering devices with mDNS for 5 seconds...
,,,

Does not find anything. Odd thing is that my Robot Vacuum works with the Xiaomi Miot Auto integration and also it can detect my Air Fryer but just says unavailable with auto or token and cloud or local.

**Comment by evlo** [comment]
Not that I use remote for this thing, but just currious:  can the 4l version be turned on remotely if the display / device is off?
