### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by GentleHoneyLover** [tsunglung/XiaomiAirFryer#22]
Hello,

Trying to configure the integration but it fails. Tried both methods (login + password and IP + token). The Fryer is on and connected to wi-fi. I can control it via the Mi app.

Can you please help! Thanks a ton!

NAME: Mi Smart Air Fryer 3.5L
MODEL: careli.fryer.maf07
HASS: 2024.2.2 (running in Docker)
Integration installed via HACS.

<img width="582" alt="Screenshot 2024-02-22 at 20 03 02" src="https://github.com/tsunglung/XiaomiAirFryer/assets/38346023/8f017fbb-2087-45ae-a22e-363c960a8349">
<img width="583" alt="Screenshot 2024-02-22 at 20 05 21" src="https://github.com/tsunglung/XiaomiAirFryer/assets/38346023/9d3a7700-7cb9-4083-9b9e-dd2a7dc10421">

**Comment by yaba** [comment]
I have the same issue. Just installed it today.

**Comment by DEDEit** [comment]
Hi, it gave me a generic error when entering the email address, I tried with the numeric ID and it worked.
Have you also checked that you have selected the correct server?
Here is the list:
- https://www.openhab.org/addons/bindings/miio/#country-servers

I hope it helps

**Comment by bolderbast** [comment]
Seems I have a similar issue

I get the same error for tha "automatic" and "manual" method. But in my case, the Airfryer is in my IOT VLAN and my Home Assistant (running in docker) is in my Internal VLAN. I have MDNS reflector running (was already in-place for Google Cast), and I have (temporarily) openend all TCP and UDP ports between the Home Assistant host and the Airfryer (bi-directional).

![image](https://github.com/tsunglung/XiaomiAirFryer/assets/78593849/defef2df-b3ef-41fb-98b4-e10c550cb167)
![image](https://github.com/tsunglung/XiaomiAirFryer/assets/78593849/892a992a-336b-4cb7-9e60-709d57efdee5)


```
Devices found for server "de" @ home "<redacted>":
   ---------
   NAME:     Airfryer
   ID:       <redacted>
   MAC:      <redacted>
   IP:       <redacted>>
   TOKEN:    <redacted>>
   MODEL:    careli.fryer.maf10a
   ---------
```


```
homeassistant  | 2024-04-29 15:12:55.862 ERROR (MainThread) [aiohttp.server] Error handling request
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/device.py", line 54, in async_connect_device
homeassistant  |     self._device_info = await self._hass.async_add_executor_job(
homeassistant  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
homeassistant  |     result = self.fn(*self.args, **self.kwargs)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/miio/click_common.py", line 183, in _wrap
homeassistant  |     self._fetch_info()
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 153, in _fetch_info
homeassistant  |     devinfo = DeviceInfo(self.send("miIO.info"))
homeassistant  |                          ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 107, in send
homeassistant  |     return self._protocol.send(
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 161, in send
homeassistant  |     self.send_handshake()
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 74, in send_handshake
homeassistant  |     raise DeviceException("Unable to discover the device %s" % self.ip)
homeassistant  | miio.exceptions.DeviceException: Unable to discover the device <redacted>
homeassistant  | 
homeassistant  | The above exception was the direct cause of the following exception:
homeassistant  | 
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
homeassistant  |     resp = await request_handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
homeassistant  |     resp = await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
homeassistant  |     return await handler(request)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
homeassistant  |     response = await handler(request)
homeassistant  |                ^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
homeassistant  |     result = await handler(request, **request.match_info)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
homeassistant  |     return await func(self, request, *args, **kwargs)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
homeassistant  |     return await super().post(request, flow_id)
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
homeassistant  |     result = await method(view, request, data, *args, **kwargs)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
homeassistant  |     result = await self._flow_mgr.async_configure(flow_id, data)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
homeassistant  |     result = await self._async_configure(flow_id, user_input)
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
homeassistant  |     result = await self._async_handle_step(
homeassistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
homeassistant  |     result: _FlowResultT = await getattr(flow, method)(user_input)
homeassistant  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/xiaomi_airfryer/config_flow.py", line 280, in async_step_cloud
homeassistant  |     return await self.async_step_connect()
homeassistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant  |   File "/config/custom_components/xiaomi_airfryer/config_flow.py", line 333, in async_step_connect
homeassistant  |     await connect_device_class.async_connect_device(self.host, self.token)
homeassistant  |   File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/device.py", line 61, in async_connect_device
homeassistant  |     raise SetupException(
homeassistant  | homeassistant.components.xiaomi_miio.const.SetupException: DeviceException during setup of xiaomi device with host <redacted>
```

**Comment by bolderbast** [comment]
Hmmm, OK. I had it internet connected to register it with the Xiaomi cloud. Then I blocked internet traffic. Now all my sensors are "Unknown" until I grant the AirFryer Internet access... I'll investigate further and I needed, I'll open a separate issue for that. Thanks for the help!

**Comment by gmcinalli** [comment]
For those with Ubiquiti devices: it seems that is now possible to masquerade NAT with the new version of Network Application. Works like a charm with my Xiaomi Smart Air Fryer 6.5L.

https://community.ui.com/releases/UniFi-Network-Application-8-3-32/54f3b506-afcf-4a7c-aba6-01a884dd9003

**Comment by GentleHoneyLover** [comment]
@gmcinalli, cool — thanks for sharing! I didn't notice it in the changeling. No need to be messing with CLI anymore :)

Would mind sharing a screenshot of how your NAT setting for XIaomi looks like in the UI?

**Comment by gmcinalli** [comment]
@GentleHoneyLover Sure! Here it is. Source is HA, destination is the AirFryer, interface is the VLAN where the fryer is located.

<img width="940" alt="image" src="https://github.com/user-attachments/assets/7984d868-b3f8-4adf-9a7b-7f63fd5612e3">

**Comment by ilmaino1984** [comment]
Same problem.
Regards

**Comment by ruimarinho** [comment]
Quick note: if you're using a UniFi gateway and NAT rules weren't making any difference, I figured out the issue in their iptables implementation and reported the bug to Ubiquiti. I am happy to announce that version v8.5.1 of the UniFi Network Controller fixes this. It's currently in Early Access and should become GA in a few weeks from now.

**Comment by gmcinalli** [comment]
@ruimarinho Really strange, I was with an older version of UniFi Network until yesterday and everything worked fine.

**Comment by GentleHoneyLover** [comment]
Same here. NAT settings via web ui work fine for me on v8.4.62

**Comment by OlafKocanda** [comment]
> @GentleHoneyLover Sure! Here it is. Source is HA, destination is the AirFryer, interface is the VLAN where the fryer is located.
> 
> <img alt="image" width="940" src="https://private-user-images.githubusercontent.com/9024983/349355413-7984d868-b3f8-4adf-9a7b-7f63fd5612e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjE1NjksIm5iZiI6MTczMzY2MTI2OSwicGF0aCI6Ii85MDI0OTgzLzM0OTM1NTQxMy03OTg0ZDg2OC1iM2Y4LTRhZGYtOWE3Yi03ZjYzZmQ1NjEyZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDhUMTIzNDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM3YTI2N2MwZTY4MDcwNGNkNWYzYmIzZTg3ZmQ0NmQ2MmVlZDYxZWY4ZDI4ZGJkMTg4NWYwYTdkOTRhNWE0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vlUU1rNCC0oLFy9fknmn1eTnfictio5_tOyX8oKpqMg">

This worked for me. Thanks so much! :)
